### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jniopencv_videoio in java.library.path due to java.lang.UnsatisfiedLinkError: ... (libgtk-x11-2.0.so.0)

### ISSUE THREAD

**Issue by RoiViber** [bytedeco/sbt-javacv#14] opened 2017-01-02 14:51 UTC
Hi,

I'm running scala (compiled using sbt) app that uses several OpenCV's functionalities. Eventually I managed to run some of them, but I still encounter the following exception:

> Name: java.lang.NoClassDefFoundError
> Message: Could not initialize class org.bytedeco.javacpp.opencv_objdetect$CascadeClassifier
> StackTrace: 

Notes:
1. My project/plugins.sbt file looks like this:
```scala
logLevel := Level.Warn
resolvers += Resolver.sonatypeRepo("releases")
addSbtPlugin("org.bytedeco" % "sbt-javacv" % "1.12")
```

2. My build.sbt looks like this:

```scala
name := "..."
version := "1.0"
scalaVersion := "2.11.8"
javaCppPresetLibs ++= Seq("opencv" -> "3.1.0", "ffmpeg" -> "3.1.2")
javaCppPlatform := Seq("linux-x86_64")
``` 

3. I'm coding+debugging on Windows machine where everything runs smoothly. Then I tried adding the _linux-x86_64 platform_ to the build.sbt as in (2) and use sbt-assembly to package my linux-ready jar. I uploaded that jar into my linux cluster, then cloned the 3.1.0 version of opencv from _https://github.com/Itseez/opencv_ and ran _cmake_, _make_ and _make install_.

4. Finally, in scala, this piece of code works great (uses org.bytedeco.javacpp.opencv_imgcodecs & org.bytedeco.javacpp.opencv_imgproc):

```scala
import org.bytedeco.javacpp.BytePointer
import org.bytedeco.javacpp.opencv_core.{Mat, _}
import org.bytedeco.javacpp.opencv_imgcodecs._
import org.bytedeco.javacpp.opencv_imgproc._
import org.bytedeco.javacpp.opencv_objdetect.CascadeClassifier
 
val bytes = ByteBuffer.wrap( /* some Byte array */ )
val imgCvMat = cvDecodeImageM(cvMat(1, bytes .array().length, CV_8UC1, new BytePointer(bytes )))
val imgMat = cvarrToMat(imgCvMat)
```

while this code:

```scala
val faceCascade = new org.bytedeco.javacpp.opencv_objdetect.CascadeClassifier( /* path to xml of classifier configuration */ )
```

fails with the following exception:

> java.lang.UnsatisfiedLinkError: no jniopencv_videoio in java.library.path
>   at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
>   at java.lang.Runtime.loadLibrary0(Runtime.java:870)
>   at java.lang.System.loadLibrary(System.java:1122)
>   at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:784)
>   at org.bytedeco.javacpp.Loader.load(Loader.java:586)
>   at org.bytedeco.javacpp.Loader.load(Loader.java:503)
>   at org.bytedeco.javacpp.opencv_videoio.<clinit>(opencv_videoio.java:14)
>   at java.lang.Class.forName0(Native Method)
>   at java.lang.Class.forName(Class.java:348)
>   at org.bytedeco.javacpp.Loader.load(Loader.java:558)
>   at org.bytedeco.javacpp.Loader.load(Loader.java:503)
>   at org.bytedeco.javacpp.opencv_objdetect$CascadeClassifier.<clinit>(opencv_objdetect.java:566)
>   ... 52 elided
> Caused by: java.lang.UnsatisfiedLinkError: /home/hadoop/.javacpp/cache/mlageinf.jar/org/bytedeco/javacpp/linux-x86_64/libjniopencv_videoio.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
>   at java.lang.ClassLoader$NativeLibrary.load(Native Method)
>   at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
>   at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
>   at java.lang.Runtime.load0(Runtime.java:809)
>   at java.lang.System.load(System.java:1086)
>   at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:767)
>   ... 60 more
> 

Note that theeres a missing libgtk-x11-2.0.so.0 - and I can't figure out what to do here

**Comment by lloydmeta** [comment] 2017-01-02 15:13
That's strange, I have not seen that error before. In the interest of being thorough, can you make sure you're using the latest JavaCPP by setting the following?

```scala
javaCppVersion := "1.3.1"
```

Also, ffmpeg's latest version is `"3.2.1"` I believe.

It might be possible that on that platform (linux-x86_64) the shared library object wasn't packaged with the presest jar. @saudet any idea?

**Comment by RoiViber** [comment] 2017-01-02 16:03
@lloydmeta thanks for the quick reply. I tried adding the version argument, same result here.
I'm using Amazon's AWS machines, and they have their own linux distribution so I also don't seem to find any way of installing this specific gtk version manually.

**Comment by RoiViber** [comment] 2017-01-02 16:23
btw, looking at /myjar.jar/org/bytedeco/javacpp/linux-x86_64/ i have a a lot of libjni*.so files, none of them contain "gtk", so apparently it isn't packaged.

**Comment by saudet** [comment] 2017-01-03 00:57
GTK comes preinstalled with pretty much any Linux distribution... except the one from Amazon that is? So it looks like we might have to do something about that. As usual, contributions are welcome!

**Comment by lloydmeta** [comment] 2017-01-03 03:46
I'm closing this issue for now because it doesn't seem to be related to the SBT plugin.

The discussion should probably continue on the javacpp-presets project, or [this PR](https://github.com/bytedeco/javacpp-presets/pull/349).

**Closed as completed by lloydmeta** 2017-01-03 03:46 UTC

**Comment by LtHummus** [comment] 2021-11-07 20:05
For anyone that stumbles upon this later looking for answers:

If you are on Amazon Linux 2, `sudo yum install gtk2-devel`

**Comment by saudet** [comment] 2021-11-08 00:27
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/593
