### ISSUE TITLE
Include path of binaries creating an error

### ISSUE THREAD

**Issue by nmolenaar** [bytedeco/sbt-javacv#12] opened 2016-11-02 06:56 UTC
With version 1.10 (sbt-opencv) w're getting (2 developer different machines) the following error regarding the including of the binaries.

```
com.google.inject.CreationException: Unable to create injector, see the following errors:
[info] 
[info] 1) Error injecting constructor, java.lang.UnsatisfiedLinkError: no jniopencv_face in java.library.path
[info]   at library.GenderRecognition.<init>(GenderRecognition.scala:109)
[info]   at Module.configure(Module.scala:21) (via modules: com.google.inject.util.Modules$OverrideModule -> Module)
[info]   while locating library.GenderRecognition
[info] 
[info] 1 error
[info]   at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
[info]   at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
[info]   at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
[info]   at com.google.inject.Guice.createInjector(Guice.java:96)
[info]   at com.google.inject.Guice.createInjector(Guice.java:84)
[info]   at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:181)
[info]   at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:123)
[info]   at org.scalatestplus.play.OneAppPerTest$class.newAppForTest(OneAppPerTest.scala:71)
[info]   at FaceDetectionTest.newAppForTest(FaceDetectionTest.scala:11)
[info]   at org.scalatestplus.play.OneAppPerTest$class.withFixture(OneAppPerTest.scala:88)
[info]   ...
**[info]   Cause: java.lang.UnsatisfiedLinkError: no jniopencv_face in java.library.path**
[info]   at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
[info]   at java.lang.Runtime.loadLibrary0(Runtime.java:870)
[info]   at java.lang.System.loadLibrary(System.java:1122)
[info]   at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:727)
[info]   at org.bytedeco.javacpp.Loader.load(Loader.java:502)
[info]   at org.bytedeco.javacpp.Loader.load(Loader.java:419)
[info]   at org.bytedeco.javacpp.opencv_face.<clinit>(opencv_face.java:13)
[info]   at library.GenderRecognition.<init>(GenderRecognition.scala:21)
[info]   at library.GenderRecognition$$FastClassByGuice$$53415250.newInstance(<generated>)
[info]   at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
[info]   ...
[info]   Cause: java.lang.UnsatisfiedLinkError: /private/var/folders/td/9xc91ttn3bx5m0f0wr7bh9900000gn/T/javacpp45557842528326/libjniopencv_face.dylib: dlopen(/private/var/folders/td/9xc91ttn3bx5m0f0wr7bh9900000gn/T/javacpp45557842528326/libjniopencv_face.dylib, 1): Library not loaded: @rpath/libopencv_objdetect.3.1.dylib
[info]   Referenced from: **/private/var/folders/td/9xc91ttn3bx5m0f0wr7bh9900000gn/T/javacpp45557842528326/./libopencv_face.3.1.dylib**
[info]   Reason: image not found
[info]   at java.lang.ClassLoader$NativeLibrary.load(Native Method)
[info]   at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
[info]   at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
[info]   at java.lang.Runtime.load0(Runtime.java:809)
[info]   at java.lang.System.load(System.java:1086)
[info]   at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:710)
[info]   at org.bytedeco.javacpp.Loader.load(Loader.java:502)
[info]   at org.bytedeco.javacpp.Loader.load(Loader.java:419)
[info]   at org.bytedeco.javacpp.opencv_face.<clinit>(opencv_face.java:13)
[info]   at library.GenderRecognition.<init>(GenderRecognition.scala:21)
```

**Comment by saudet** [comment] 2016-11-02 07:03
Duplicate of https://github.com/bytedeco/javacv/issues/470
Workaround: https://github.com/bytedeco/javacv/issues/470#issuecomment-236154627

**Closed as completed by saudet** 2016-11-02 07:03 UTC
Labels: bug, duplicate
